# -*- coding: utf-8 -*-
"""Python_project_by_Nimish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RuFtIrDUnX3CKXIMq5TIAYUVu8H92NIP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Hotel Bookings.csv')
df.head()

df

pd.set_option('display.max_rows',100)

pd.set_option('display.max_columns',100)

df.shape

df.info()

df.info

df.select_dtypes(include='object')

df.select_dtypes(include=['int','float'])

# @title Treating null values

df.isnull().sum()

#to check the null values in the dataset

df['company'].value_counts()

df['company'].countm()

#for rows
df.shape[0]

avg=df['company'].isnull().sum()/df.shape[0]*100
avg

for i in df:
  print(df[i].isnull().sum()/df.shape[0]*100)

#drop company column
df.drop(columns=['company'],inplace=True)

#check
df.info
df.columns

df['agent'].unique()

df.drop(columns=['agent'],inplace=True)

df.isnull().sum()

df['country'].mode()[0]

df['country'].fillna(value=df['country'].mode()[0],inplace=True)

df.isnull().sum()

df=df.drop(columns=['children'],axis=0)

# @title Null Value is treated
df.isnull().sum()

# @title  Outlier
num_var=df.select_dtypes(exclude='object')
for i in num_var:
  q1=df[i].quantile(0.25)
  q3=df[i].quantile(0.75)
  IQR=q3-q1
  ul=q3+1.5*IQR
  ll=q1-1.5*IQR
  print(IQR,'IQR')
  print(ul,'ul')
  print(ll,'ll')
  print(i,df.shape[0]-df[(df[i]<ul) & (df[i]>ll)].shape[0])
  print('')

df['required_car_parking_spaces'].unique()

df['required_car_parking_spaces'].value_counts()

df['previous_bookings_not_canceled'].value_counts()

df['hotel'].value_counts()

sns.barplot(x='hotel',y='is_canceled',data=df)